Cargo.lock, Cargo.toml, Makefile, src/main.rs, src/misc.rs
close #9
- refactor
- add test
- fix preview bug
=> fix extract command method

src/misc.rs
=> hide fzf window when make command executed

Makefile, src/main.rs
=> receive input from stdin

src/main.rs
- print selected target name to stdout
=> print selected target name to stdout

.github/workflows/rust.yml
=> Build and test on push

.github/workflows/brew-release.yml
=> automate homebrew release

src/fuzzy_finder/fuzzy_finder.rs
Don't know why it didn't come into my mind in the first place 🙄
=> refactor: optimize Linux grep workaround

Makefile, src/fuzzy_finder/fuzzy_finder.rs
close #51
Position of preview window will be configurable in the future.
| Before | After |
|<img width="886" alt=" 2023-09-02 at 0 18 00" src="https://github.com/kyu08/fzf-make/assets/49891479/6dae1240-cea3-4bb2-9482-eab811131c08">|<img width="886" alt=" 2023-09-02 at 0 16 52" src="https://github.com/kyu08/fzf-make/assets/49891479/a9baf4f7-7bcb-44fd-846c-a028f2236373">|
=> Make preview window showed on top by default

CREDITS, Cargo.lock, Cargo.toml, src/fuzzy_finder/fuzzy_finder.rs
close #47 
The color will be configurable via config file in the future.
| Before | After|
|<img width="304" alt="image" src="https://github.com/kyu08/fzf-make/assets/49891479/3da1c865-6dd2-4596-8e47-24624e3523d3">|<img width="268" alt="image" src="https://github.com/kyu08/fzf-make/assets/49891479/ace04814-3d66-4116-8209-04f16784aabf">|
=> Make target to be executed display prettier #47

Cargo.toml
=> Add authors, description and license to `Cargo.toml`

src/models/target.rs
=> Ignore line like `hoge := 1`

.github/workflows/brew-release.yml, .github/workflows/cargo-publish.yml, .github/workflows/test.yml
=> Run `cargo publish` on CI

README.md, doc/README-de.md
Added the german translation for the readme-file.
Also implemented the linking to the different translations as mentioned in #106.
=> Add german translation

README.md, doc/README-de.md
i have commited this issue for you. Can you accept to merge it.
=> Add crates.io badge to README 

doc/README-de.md
=> fix README-de.md

src/models/makefile.rs, src/models/target.rs, src/models/util.rs
=> Add error handling when the path passed to include directive could not be found #150

README.md, _typos.toml, doc/README-de.md, doc/README-fr.md
Find out there is a Deutsch readme translation available, so why not add a french one? (I'm French)
=> Add french translation of the README.md

README.md, doc/README-de.md, doc/README-fr.md
=> Add `--locked` flag to `cargo install`

src/models/target.rs
=> Allow a target with only one letter

Makefile, src/usecase/fzf_make/app.rs
=> Application panics when no target is selected and return key pressed #158

Makefile
=> Simplify release #95

src/usecase/fzf_make/app.rs, src/usecase/fzf_make/ui.rs
- Fixed problem that error message is displayed when quitting
- Show nothing on preview window when there is no target to select
=> Fixed problem that error message is displayed when quitting, show nothing on preview window when there is no target to select

Cargo.toml, Makefile, rust-toolchain.toml
- chore
- Add `rust-toolchain.toml`
=> Add `rust-toolchain.toml`

src/file/toml.rs, src/model/histories.rs, src/usecase/fzf_make/app.rs
=> History file does not been saved when history file does not exist #205

src/usecase/fzf_make/app.rs
=> Select a target when space key pressed on History pane #209

README.md, doc/README-de.md, doc/README-fr.md, src/controller/controller_main.rs, src/main.rs, src/model/histories.rs, src/usecase/execute_make_command.rs, src/usecase/fzf_make/app.rs, src/usecase/help.rs, src/usecase/mod.rs, src/usecase/repeat.rs
=> Add command `fzf-make --repeat` to execute the target last executed

src/usecase/fzf_make/ui.rs
Resolves #226
| Before | After |
|<img width="743" alt="image" src="https://github.com/kyu08/fzf-make/assets/49891479/fffc8b4b-57bd-46ec-bf04-58638dd17864">  | <img width="742" alt="image" src="https://github.com/kyu08/fzf-make/assets/49891479/8e6b967a-fe5b-4740-8b76-66f0c998666f">|
=> Change the position of history pane #226

.github/workflows/fmt.yml, Makefile
=> Ensure cargo fmt Is executed in CI #248

README.md, doc/README-de.md, doc/README-fr.md
=> Delete `brew tap kyu08/tap` from `README.md` #251

src/usecase/fzf_make/ui.rs
| Before | <img width="1500" alt="image" src="https://github.com/kyu08/fzf-make/assets/49891479/b5f50170-7afe-493e-a0ea-e02dc5406b40">|
| After | <img width="1500" alt="image" src="https://github.com/kyu08/fzf-make/assets/49891479/becf3576-e721-4263-9799-660512e8a16c"> |
=> feat: Add emojis to the pane title

src/usecase/fzf_make/ui.rs
Resolves #260
- Made selected pane color light green
- Disable highlight of the selected target
- Made selected pane's border bold
|Before|<img width="1518" alt=" 2024-05-22 at 0 16 36" src="https://github.com/kyu08/fzf-make/assets/49891479/40865bfa-b57d-41e8-9b33-0f6457f903cb">|
|---|---|
|After|<img width="1488" alt=" 2024-05-22 at 0 16 17" src="https://github.com/kyu08/fzf-make/assets/49891479/55181b6c-c614-4a2b-ac57-52526abb5cd0">|
=> chore(UI): Change some styles

README.md, doc/README-de.md, doc/README-fr.md, src/controller/controller_main.rs, src/usecase/fzf_make/app.rs, src/usecase/fzf_make/config.rs, src/usecase/fzf_make/mod.rs, src/usecase/help.rs, src/usecase/history.rs, src/usecase/mod.rs, src/usecase/repeat.rs
=> feat: add `--focus-history` option

src/usecase/fzf_make/ui.rs
This PR will be merged when https://github.com/rhysd/tui-textarea/pull/73 is merged.
=> chore(ui): show placeholder on search pane

README.md, doc/README-de.md, doc/README-fr.md
=> Add "crate.io Downloads" to README

src/err/any_to_string.rs, src/err/mod.rs, src/file/mod.rs, src/file/path_to_content.rs, src/file/toml.rs, src/file/toml_old.rs, src/main.rs, src/usecase/tui/app.rs
Resolves #326 #151.
Enhancement for #315.
=> When the history file type is the old format, rewrite it using the new format

src/usecase/tui/app.rs
=> fix(bug): no command is selected when delete character #328

src/usecase/tui/app.rs
=> fix(chore): fix lint error

README.md, doc/README-de.md, doc/README-fr.md, src/usecase/help.rs
=> docs(pnpm): update docs for supporting pnpm

src/usecase/repeat.rs
=> feat(repeat): show command when repeat #338

src/usecase/tui/app.rs
=> feat(error): show error message when no task runner found

src/model/js_package_manager/pnpm.rs, test_data/package.json
=> feat(pnpm): do not ignore pattern like `pnpm run --filter app1 run test`

src/usecase/tui/app.rs
=> fix(lint): elide unnecessary lifetimes

Makefile, src/model/js_package_manager/js_package_manager_main.rs, src/model/js_package_manager/yarn.rs
=> feat(yarn): support launching inside workspace

src/model/js_package_manager/yarn.rs
Resolves #386
https://github.com/Homebrew/homebrew-core/pull/200814
=> fix(yarn): improve Yarn version detection with better error handling

src/model/js_package_manager/yarn.rs
=> fix(yarn): fzf-make renders empty preview pane when fzf-make is launched in the directory which does not have `package.json`

src/usecase/tui/app.rs
1. `$ fzf-make` in the dir which does not have runner
2. TUI is shown just for a moment
3. Error message is shown
1. `$ fzf-make` in the dir which does not have runner
2. Error message is shown
=> fix(app): enter TUI after initializing `model`

README.md
context: https://github.com/kyu08/fzf-make/issues/195#issuecomment-2533437894
=> docs(readme): update brew command #195

.gitignore, Makefile, src/file/toml.rs
=> chore(refactor): move `test_dir` to inside of `test_data`

.github/workflows/brew-release.yml
=> feat(cd): send a PR to homebrew-core when a new version released

Makefile, src/usecase/tui/ui.rs
| Before | After |
|<img width="1680" alt="image" src="https://github.com/user-attachments/assets/95e31418-be3c-49b3-abcb-fb50d4f1769f" />|<img width="1680" alt="image" src="https://github.com/user-attachments/assets/a5b1b7b9-a27a-416a-b910-6ca5ee810631" />|
=> fix(ui): fix background issue color with Neovim terminal

.github/workflows/brew-release.yml
https://github.com/kyu08/fzf-make/actions/runs/12468566650/job/34799985841
=> fix(cd_brew): fix branch name of homebrew-core

flake.lock, flake.nix
=> fix(flake): Update lock and add missing vendor hash

src/usecase/tui/app.rs
=> fix(update_informer): check new version interval should be 24 hours

.github/workflows/fmt.yml, Makefile, rustfmt.toml, src/controller/controller_main.rs, src/file/toml_old.rs, src/model/js_package_manager/pnpm.rs, src/model/js_package_manager/yarn.rs, src/model/just/just_main.rs, src/model/make/make_main.rs, src/model/runner_type.rs, src/usecase/fzf_make.rs, src/usecase/tui/app.rs, src/usecase/tui/ui.rs
ref: https://github.com/rust-lang/rustfmt/blob/master/Configurations.md
=> chore(fmt): `group_imports = "One"`, `imports_granularity = "Crate"`

renovate.json
=> chore(renovate): update dependencies individually

.github/workflows/fmt.yml, .github/workflows/lint.yml, .github/workflows/test.yml, rust-toolchain.toml
=> chore(toolchain): specify toolchain versions

src/usecase/tui/app.rs
=> fix(ui): key input is blocked sometimes

src/usecase/tui/ui.rs
=> chore(ui): add emoji to the title of additional arguments popup window

rust-toolchain.toml, src/usecase/tui/app.rs, src/usecase/tui/ui.rs
=> fix(deps): bump rustc to stable(1.86.0)

Cargo.toml, src/file/path_to_content.rs, src/model/file_util.rs, src/model/js_package_manager/pnpm.rs, src/model/js_package_manager/yarn.rs, src/model/just/just_main.rs, src/model/make/make_main.rs, src/model/runner_type.rs, src/usecase/fzf_make.rs, src/usecase/help.rs, src/usecase/history.rs, src/usecase/invalid_arg.rs, src/usecase/repeat.rs, src/usecase/tui/app.rs, src/usecase/tui/ui.rs, src/usecase/version.rs
=> chore(deps): bump rust edition to 2024

README.md
=> docs(readme): add budge of Rust and Homebrew to `README.md`

src/usecase/tui/app.rs
=> fix(ui): `<tab>` is enable accidentally when the additional arguments popup is opened

.github/workflows/detect-unused-dependencies.yml
=> chore(ci): detect unused dependencies

license.html
https://github.com/kyu08/fzf-make/pull/495
=> chore(release): bump to v0.59.0 for license.html

Cargo.toml
=> chore(cargo): specify `dev-dependencies` properly

Cargo.toml
=> chore(cargo): update `exclude` field

.github/workflows/detect-unused-dependencies.yml
https://github.com/bnjbvr/cargo-machete/pull/188
https://github.com/bnjbvr/cargo-machete/discussions/190
=> chore(ci): bump cargo-machete action

Makefile
SSIA
To reduce environmental differences among developers and CI.
It is no problem if CI passes.
=> chore(make): pin the version of the tool using in `Makefile`

renovate.json
=> chore(renovate): create PRs only if the version is older than 30 days
