src/fuzzy_finder/fuzzy_finder.rs

fix: show file names for grep command on Linux

---

.github/workflows/brew-release.yml

This PR makes `url` of formula to format like `https://github.com/OWNER/REPO/archive/refs/tags/<tag-name>.tar.gz`.
```md
download-url: the package download URL for the Homebrew formula.
Defaults to https://github.com/OWNER/REPO/archive/refs/tags/<tag-name>.tar.gz, where OWNER/REPO is the repository that is running the Actions workflow.
```
https://github.com/mislav/bump-homebrew-formula-action

Build when brew install executed

---

.github/workflows/lint.yml

Runs `cargo fmt` and `cargo clippy` in CI 
and close #74

ci: add linting

---

.github/workflows/lint.yml

Closes #100 Treat clippy's warning as errors
##Description:
This pull request updates the .github/workflows/lint.yml file to modify the command used to run cargo clippy. The change is aimed at including the -D warnings flag to control which lints are shown and adding a . to specify the target directory for linting.
##Changes Made:
* Updated the lint.yml file to run cargo clippy with the -D warnings flag.
* Added a . to specify the target directory for linting.
##Testing:
I have tested this change locally to ensure that it works as expected. The modified command correctly lints the code with only the warning-level lints within the current directory.

Treat clippy's warning as errors

---

src/usecase/fzf_make/app.rs

It seems like that frequency of a screen blinking decreases after polling duration longer.

Longer polling duration #124

---

flake.lock
flake.nix

The current lockfile references `rustc --version`: `1.69`, but the MSRV of `ratatui` is `1.70`.
This update references `rustc --version`: `1.73`.
This makes it possible again to build `fzf-make` through the referenced flake.

fix update flake dependencies

---

flake.nix

Read the build version information directly from `Cargo.toml`, elimitating the need for manually bumping.

fix nix version information

---

src/usecase/fzf_make/app.rs

Application panics when ↓ / ↑ is inputted when there is no targets to select #188

---

flake.nix

Bring minor improvement the the `flake.nix`:
- Use `devShell` (singular) attribute instead of `devShells` (list)
- Resolve dev shell dependencies from the `fzf-make` package inputs.
- Added nixpkgs-fmt to ensure a proper flake formatting
- Use direct path from `Cargo.toml`
- Update package declaration to reflect nixpkgs

Improve the flake decalaration

---

flake.nix

The flake output `devShell` has been deprecated in favor of `devShells` for 2 years now:
https://nixos.org/manual/nix/stable/release-notes/rl-2.7.html?highlight=devShell#release-27-2022-03-07
Nix itself already warns about this, and it is feasible that at some point the backwards compatibility will be dropped.

fix: devShells default output

---

flake.lock
flake.nix

- Resolves #239 
- Added `typos` as it is used within the default Makefile rule

Fix nix devshell dependencies

---

Cargo.lock

The `v.0.1.9` release had a little bit of breaking changes, and I wanted to check if you are affected by it.
I tested against main, and I don't see any regressions.

Update `tui-term` to `v.0.1.9`

---

flake.nix
src/model/target.rs

Hi, I tried to implement the `define` block skip myself, as it is a feature that I would like to have.
- Resolves #236
> *Tested on glibc's Makefile, and seems skip define properly.*
> [!NOTE]
> *With some background in C, I'm still unfamiliar with Rust, so I focused on a simple implementation that works. It might not be fancy, and not be the best way to pull this off, so I rely on your expertise for some feedback.*

Add define block skip

---

src/usecase/fzf_make/ui.rs

Resolves #266 
|Before|<img width="1504" alt="image" src="https://github.com/kyu08/fzf-make/assets/49891479/57f9630d-33ae-4ed5-a153-ae1823c90a98">|
|---|---|
|After|<img width="1500" alt="image" src="https://github.com/kyu08/fzf-make/assets/49891479/7d3eee69-7622-4dfc-b5b6-d05ebc7193c9">|

A row including 🛠️ is shifted in alacritty #266

---

src/usecase/fzf_make/ui.rs

Fixed this error from clippy.
```shell
error: match can be simplified with `.unwrap_or_default()`
--> src/usecase/fzf_make/ui.rs:196:13
|
[196](https://github.com/kyu08/fzf-make/actions/runs/9626356023/job/26552236621#step:3:197) |       let h = match model.get_history() {
|  _____________^
[197](https://github.com/kyu08/fzf-make/actions/runs/9626356023/job/26552236621#step:3:198) | |         Some(h) => h,
198 | |         None => vec![],
[199](https://github.com/kyu08/fzf-make/actions/runs/9626356023/job/26552236621#step:3:200) | |     };
| |_____^ help: replace it with: `model.get_history().unwrap_or_default()`
|
= help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#manual_unwrap_or_default
= note: `-D clippy::manual-unwrap-or-default` implied by …
```

chore(ci): fix lint error to use `unwrap_or_default()`

---

src/usecase/fzf_make/app.rs

Resolves Issue https://github.com/kyu08/fzf-make/issues/312

fix(lint): fix lint error `error: match can be simplified with .unwrap_or_default()` #312

---

CREDITS
Cargo.lock
Cargo.toml
src/controller/controller_main.rs
src/file/toml.rs
src/main.rs
src/model/command.rs
src/model/file_util.rs
src/model/histories.rs
src/model/make.rs
src/model/runner.rs
src/model/runner_type.rs
src/model/target.rs
src/usecase/help.rs
src/usecase/repeat.rs
src/usecase/tui/app.rs
src/usecase/tui/ui.rs

Refactor for #315.
Resolves #323.
Just run latest command. New history file format enables it.
```toml
[[histories]]
path = "path/to/hoge"
[[histories.commands]]
runner = "make"
command = "run"
[[histories.commands]]
runner = "make"
command = "test"
[[histories.commands]]
runner = "pnpm"
command = "install"
[[histories]]
path = "path/to/fuga"
[[histories.commands]]
runner = "yarn"
command = "run"
[[histories.commands]]
runner = "make"
command = "test"
[[histories.commands]]
runner = "bun"
command = "test"
```
<details><summary>A format not adopted</summary>
<p>
```toml
[[histories]]
path = "path/to/hoge"
[[histories.runners]]
name = "make"
commands = ["run", "test"]
[[histories.runners]]
name = "pnpm"
commands = ["install", "test"]
[[histories]]
path = "path/to/fuga"
[[histories.runners]] …
```

update(history): update history file format to handler multiple task runner like pnpm, yarn, e.t.c. #315

---

.gitignore
CREDITS
Cargo.lock
Cargo.toml
Makefile
src/model/js_package_manager.rs
src/model/make.rs
src/model/mod.rs
src/model/pnpm.rs
src/model/runner.rs
src/model/runner_type.rs
src/usecase/tui/app.rs
test_data/Makefile
test_data/makefiles/test.mk
test_data/package.json

Resolves #331
1. Use https://github.com/MaulingMonkey/json-spanned-value/blob/db682d75b30438866b6e9d02f1187918eb329e1b/examples/demo.rs.
2. Implement by myself. It may be naive, but there will be no big problem.

feat(runner): support pnpm

---

src/model/js_package_manager/yarn.rs

Startup speed become faster when `package.json` is missing. 🏎️

fix(yarn): add early return when `package.json` is missing

---

README.md

Resolves #301 
* Added a section for `Example aliases` in the README.
* Removed paths to non-English versions of README.md and retained only the English version.

Add "Example aliases" to README

---

CREDITS
Cargo.lock
Cargo.toml
Makefile
README.md
flake.nix
src/usecase/tui/app.rs
src/usecase/tui/ui.rs

Resolves #234, resolves #124, resolves #144, resolves #49
When the preview file includes tab characters, rendering crashes.
issue: https://github.com/ratatui/ratatui/issues/876
Just replaced `"\t"` with `"    "`.
```rs
let source_lines: Vec<_> = reader
.lines()
.skip(start - 1)
.take(end - start + 1)
.map(|line| line.unwrap().replace("\t", "    "))
.collect();
```

fix(ui): use trishume/syntect to highligh files instead of using bat with tui-term

---

Cargo.lock
Cargo.toml

fix(cd): specify tree-sitter-just's the version instead of commit hash in `cargo.toml`

---

.devcontainer/devcontainer.json

fzf-make is no longer depend on `bat`.

chore(dev_container): remove bat installation command

---

src/usecase/tui/app.rs

feat(ui): map ctrl + n/p to move cursor up/down

---

src/usecase/tui/app.rs

#467
According to claude, original implementation has a problem.
Since this is my hobby project, so I won't conduct a detailed investigation now that I've confirmed the problem has been actually solved.
Following content is from claude sonnet 3.7.
The current implementation of the event handling function has an issue where key inputs can be missed after a timeout occurs. This happens because of how the `poll` and `read` functions are evaluated together in a tuple pattern match.
```rust
fn handle_event(model: &Model) -> io::Result<Option<Message>> {
match (crossterm::event::poll(std::time::Duration::from_millis(10000))?, crossterm::event::read()?) {
(true, crossterm::event::Event::Key(key)) => Ok(model.handle_key_input(key)),
_ => Ok(None),
}
}
```
The issue occurs because:
1. When `poll` …

fix(ui): fix key blocking #467

---

README.md
docs/MANUAL_TEST_CASES.md
src/file/toml.rs
src/model/command.rs
src/model/histories.rs
src/model/js_package_manager/js_package_manager_main.rs
src/model/js_package_manager/pnpm.rs
src/model/js_package_manager/yarn.rs
src/model/just/just_main.rs
src/model/make/make_main.rs
src/model/make/target.rs
src/model/runner.rs
src/model/runner_type.rs
src/usecase/repeat.rs
src/usecase/tui/app.rs
src/usecase/tui/ui.rs
test_data/just/justfile
test_data/make/Makefile

Resolves #364 
1. Press `Ctrl + O` to open additional arguments popup.
1. Enter additional arguments.
1. Press `Enter` to execute the command.
1. The command is executed with the additional arguments.
<details><summary>Test</summary>
<p>
</p>
</details>

feat(command): support passing additional arguments to the command

---

src/file/toml.rs
src/model/runner_type.rs

refactor(from_trait): impl From trait properly

---

.github/workflows/brew-release.yml
.github/workflows/check-licenses.yml
.github/workflows/spell-check.yml
Makefile
deny.toml

chore(license): check license using cargo-deny

---

.gitattributes

chore(git): ignore html files for repository language statistics

---

CREDITS.html
Cargo.lock
Cargo.toml
about.toml
deny.toml

I checked that these licenses are copy-right and no inconvenience for this project.
- Unicode-3.0: https://www.unicode.org/license.txt
- CDLA-Permissive-2.0: https://cdla.dev/permissive-2-0/
- Zlib: https://en.wikipedia.org/wiki/Zlib_License

fix(deps): update rust crate update-informer to v1.2.0

---

.github/workflows/check-license-file.yml

This workflow sometimes fails, and retrying resolves it.

chore(ci): add retry mechanism to checking license file workflow

---

src/usecase/tui/app.rs
src/usecase/tui/ui.rs

Added signal handling to properly respond to Ctrl+C (SIGINT). The application now gracefully terminates when the user presses Ctrl+C, which is the standard expected behavior for terminal applications.
Currently, the application does not respond to Ctrl+C, which violates standard Unix/terminal conventions and creates a poor user experience. Users expect Ctrl+C to interrupt and exit a running terminal application. This PR ensures the application behaves like other well-designed CLI tools and respects standard terminal signal handling.
I tested that ctrl-c terminates in both the execution & history mode.

feature: support quit with ctrl-c

---

.github/workflows/check-license-file.yml
CREDITS.html
Makefile
about.toml

According to `cargo-about generate --help`, --frozen seems reducing flakeyness.
```man
--offline
Run without accessing the network.
In addition to cargo not fetching crates, this will mean that only local files will be crawled for license information. 1. clearlydefined.io will not be used, so some more ambiguous/complicated license files might be ignored 2. Crates that are improperly packaged and don't contain their LICENSE file(s) will fallback to the default license file, missing eg. copyright information in the license that would be retrieved from the original git repo for the crate in question
--locked
Assert that `Cargo.lock` will remain unchanged
--frozen
Equivalent to specifying both `--locked` and `--offline`
--fail
Exit with a non-zero exit code when failing to read, synthesize, …
```

chore(license): update license file

---

.github/workflows/check-license-file.yml
CREDITS.html
Makefile
about.toml

Closes https://github.com/kyu08/fzf-make/issues/519.
According to `cargo-about generate --help`, --frozen seems reducing flakeyness because it make cargo-about not accessing to clearly defined.
```man
--offline
Run without accessing the network.
In addition to cargo not fetching crates, this will mean that only local files will be crawled for license information. 1. clearlydefined.io will not be used, so some more ambiguous/complicated license files might be ignored 2. Crates that are improperly packaged and don't contain their LICENSE file(s) will fallback to the default license file, missing eg. copyright information in the license that would be retrieved from the original git repo for the crate in question
--locked
Assert that `Cargo.lock` will remain unchanged
--frozen
Equivalent to …
```

chore(license): update license file without clearly defined
